# Collatz Sequence:
# The Collatz sequence, also known as the 3n+1 problem, is a sequence of numbers generated by starting with any positive integer N and following two simple rules:
# if N is even, divide it by 2; if N is odd, multiply it by 3 and add 1. The conjecture states that no matter which positive integer you start with, you will always eventually reach the number 1.

def collatz(number):
    if number % 2 == 0:
        return number // 2
    elif number % 2 == 1:
        return 3 * number + 1
    else:
        raise ValueError("Input must be a positive integer.")

def main():
    try:
        number = int(input('Enter a positive integer:'))
        if number <= 0:
            raise ValueError("Input must be a positive integer.")
        print(f'Collatz sequence starting from {number}:')
        while number != 1:
            print(number, end=' ')
            number = collatz(number)
        print(1)
    except ValueError as e:
        print(f"Error: {e}")

main()
